name: Deploy Bokeh Dashboard

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install bokeh pandas

      - name: Prepare gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git rm -rf . || echo "Nothing to delete"
          git commit -m "Clean gh-pages" --allow-empty
          git push origin gh-pages

      - name: Generate static content
        run: |
          # Crear un index.html básico con instrucciones
          echo "<html><body>" > index.html
          echo "<h1>Superstore Dashboard</h1>" >> index.html
          echo "<p>Esta aplicación requiere un servidor Bokeh para funcionar.</p>" >> index.html
          echo "<p>Para ver el dashboard interactivo, ejecuta localmente:</p>" >> index.html
          echo "<code>bokeh serve app.py --show</code>" >> index.html
          echo "</body></html>" >> index.html

      - name: Deploy to gh-pages
        run: |
          git checkout gh-pages
          # Forzar la eliminación de todo el contenido existente
          rm -rf *
          # Mover el nuevo index.html
          mv ../index.html .
          git add .
          git commit -m "Deploy static info page $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin gh-pages