name: Deploy Bokeh to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el código
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Configura Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      # 3. Instala dependencias
      - name: Install dependencies
        run: |
          pip install bokeh pandas
          
      # 4. Configura Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # 5. Prepara la rama gh-pages
      - name: Prepare gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git rm -rf . || echo "Nothing to delete"
          git commit -m "Clean gh-pages" --allow-empty
          git push origin gh-pages

      # 6. Ejecuta Bokeh y captura el HTML
      - name: Run Bokeh and capture output
        run: |
          # Instala xvfb para simular pantalla
          sudo apt-get install xvfb
          
          # Ejecuta Bokeh en segundo plano y captura el HTML
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          export DISPLAY=:99
          
          bokeh serve --show app.py > bokeh_output.html 2>&1 &
          sleep 15
          
          # Extrae la URL del HTML generado
          HTML_URL=$(grep -oP 'Bokeh app running at: \K.*' bokeh_output.html | head -1)
          
          # Si no funciona el método automático, generamos uno manual
          if [ -z "$HTML_URL" ]; then
            echo "<html><body>" > index.html
            echo "<h1>Superstore Dashboard</h1>" >> index.html
            echo "<p>Para ver el dashboard interactivo, ejecuta localmente:</p>" >> index.html
            echo "<code>bokeh serve app.py --show</code>" >> index.html
            echo "</body></html>" >> index.html
          else
            curl -s "$HTML_URL" > index.html
          fi

      # 7. Sube el archivo index.html a gh-pages
      - name: Deploy to gh-pages
        run: |
          git checkout gh-pages
          mv index.html .
          git add index.html
          git commit -m "Deploy Bokeh dashboard $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin gh-pages