name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Important to get all branches

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bokeh

    - name: Set up Git user
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Prepare gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages
        git rm -rf . || echo "Nothing to delete"
        git commit -m "Clean gh-pages branch" --allow-empty

    - name: Generate static files
      run: |
        # Convert Bokeh app to static HTML
        python -m bokeh html app.py --outdir ./output
        
        # Move files to root
        mv ./output/* .
        rm -rf output

    - name: Commit and push
      run: |
        git add .
        git commit -m "Deploy Bokeh app $(date +'%Y-%m-%d %H:%M:%S')"
        git push origin gh-pages