name: Deploy Static Dashboard

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bokeh pandas selenium webdriver-manager
          sudo apt-get install -y chromium-browser

      - name: Generate static screenshot
        run: |
          # Iniciar servidor Bokeh en background
          python -m bokeh serve app.py --port 5006 --allow-websocket-origin=* &
          sleep 10
          
          # Capturar screenshot con Selenium
          python -c "
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          options = Options()
          options.add_argument('--headless')
          options.add_argument('--no-sandbox')
          options.add_argument('--disable-dev-shm-usage')
          driver = webdriver.Chrome(options=options)
          driver.get('http://localhost:5006/app')
          driver.maximize_window()
          driver.save_screenshot('dashboard.png')
          driver.quit()
          "

      - name: Create HTML file
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>Superstore Dashboard</title>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <style>body { margin: 0; padding: 20px; } img { width: 100%; }</style>
          </head>
          <body>
            <h1>Superstore Dashboard</h1>
            <img src="dashboard.png" alt="Dashboard">
            <p>Última actualización: $(date)</p>
          </body>
          </html>' > index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          force_orphan: true