name: Deploy Redirect Page

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Prepare gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          find . -not -path '*/\.git*' -delete
          git add .
          git commit -m "Clean gh-pages" --allow-empty
          git push origin gh-pages

      - name: Create redirect page
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head>
            <title>Superstore Dashboard</title>
            <meta http-equiv="refresh" content="0; url=https://bokeh-leyva.onrender.com/app" />
            <style>
              body { font-family: Arial, sans-serif; text-align: center; padding: 50px; }
              .spinner { margin: 40px auto; width: 50px; height: 50px; border: 5px solid #f3f3f3; border-top: 5px solid #3498db; border-radius: 50%; animation: spin 1s linear infinite; }
              @keyframes spin { 0% { transform: rotate(0deg); } 100% { transform: rotate(360deg); } }
            </style>
          </head>
          <body>
            <h1>Redirigiendo al Dashboard...</h1>
            <div class="spinner"></div>
            <p>Si no eres redirigido automáticamente, <a href="https://bokeh-leyva.onrender.com/app">haz clic aquí</a>.</p>
          </body>
          </html>' > index.html

      - name: Deploy to gh-pages
        run: |
          git checkout gh-pages
          git add index.html
          git commit -m "Deploy redirect to Render $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin gh-pages