name: Deploy Dashboard
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          sudo apt-get install -y chromium-browser
          pip install bokeh pandas selenium
          
      - name: Take screenshot
        run: |
          python -m bokeh serve app.py --port 5006 --allow-websocket-origin=* &
          sleep 20
          python -c "
          from selenium import webdriver
          options = webdriver.ChromeOptions()
          options.add_argument('--headless')
          driver = webdriver.Chrome(options=options)
          driver.get('http://localhost:5006/app')
          driver.save_screenshot('dashboard.png')
          driver.quit()
          "
          
      - name: Create page
        run: |
          echo '<!DOCTYPE html>
          <html>
          <head><title>Dashboard</title></head>
          <body>
            <img src="dashboard.png" style="width:100%">
          </body>
          </html>' > index.html
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./