name: Deploy Bokeh App to GitHub Pages

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene un nombre diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # O la versión que necesites

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bokeh pandas  # Instala las dependencias necesarias para ejecutar el app

    - name: Create the Bokeh app
      run: |
        mkdir -p build
        cp app.py build/  # Copia tu archivo app.py a un directorio build

    - name: Deploy to GitHub Pages
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Token para autenticarte en GitHub
      run: |
        # Instala la herramienta de GitHub Pages
        pip install ghp-import

        # Crea el directorio de salida y compila la aplicación
        mkdir -p docs
        cp -r build/* docs/

        # Usa ghp-import para desplegar en gh-pages
        ghp-import -n -p -f docs/
